---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  labels:
    app: todos-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: boot
  selector:
    app: todos-api
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-api-ingress
spec:
  rules:
    - host: todos-api.tanzu.cloud.zwickey.net
      http:
        paths:
          - backend:
              serviceName: todos-api
              servicePort: 8081
  tls:
    - hosts:
        - todos-api.tanzu.cloud.zwickey.net
      secretName: ingress-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      name: todos-api
      labels:
        app: todos-api
    spec:
      containers:
        - image: harbor.tanzu.cloud.zwickey.net/library/todos-api:latest
          name: todos-api
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: CACHEURL
              value: "http://todos-redis.default.svc.cluster.local:8888"
            - name: BACKENDURL
              value: "http://todos-mysql.default.svc.cluster.local:9090"
