---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: todos
  labels:
    app: todos-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: boot
  selector:
    app: todos-api
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todos-api-vs
  namespace: todos
spec:
  hosts:
  - "todos-api.mesh.workload1.tanzu.zwickey.net"
  gateways:
  - todos-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: todos-api
        port:
          number: 8081  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-api-ingress
  namespace: todos
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
spec:
  rules:
    - host: todos-api.workload1.tanzu.zwickey.net
      http:
        paths:
          - backend:
              serviceName: todos-api
              servicePort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
  namespace: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      name: todos-api
      labels:
        app: todos-api
    spec:
      containers:
        - image: harbor.mgmt.tanzu.zwickey.net/library/todos-api:latest
          name: todos-api
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: CACHEURL
              value: "http://todos-redis:8888"
            - name: BACKENDURL
              value: "http://todos-postgres.mesh.workload2.tanzu.zwickey.net"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
              value: "todos-all"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
