spring:
  application:
    name: 'todos-webui'
  thymeleaf:
    cache: false
todos:
  webui:
    placeholder: "Time to wash the dog?"
    username: Adam
management:
  metrics:
    export:
      wavefront:
        step: PT10S
        reporting:
          traces: true

  endpoints:
    web:
      exposure:
        include: '*'

wavefront:
  application:
    service: ${spring.application.name}
