spring:
  application:
    name: todos-redis
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      wavefront:
        step: PT10S
        reporting:
          traces: true

server:
  port: 8888

wavefront:
  application:
    service: ${spring.application.name}
