todos:
  api:
    endpoint: http://localhost:8081
  ui:
    endpoint: http://localhost:8080

zuul:
  routes:
    ui:
      path: /**
      url:  ${todos.ui.endpoint}
      stripPrefix: false
    api:
      path: /todos/**
      url:  ${todos.api.endpoint}
      stripPrefix: true

spring:
  application:
    name: todos-edge
  cloud:
    gateway:
      routes:
      - id: todos_all_api
        uri: ${todos.api.endpoint}
        predicates:
        - Path=/todos/**
        filters:
        - SetResponseHeader=X-TODOS-CLOUD-GATEWAY-ROUTE-ID, todos_all_api
        - RewritePath=/todos/(?<path>.*), /$\{path}
      - id: todos_ui_root
        uri: ${todos.ui.endpoint}
        predicates:
        - Path=/**
server:
  port: 9999
management:
  metrics:
    export:
      wavefront:
        step: PT10S
        reporting:
          traces: true

  endpoints:
    web:
      exposure:
        include: '*'

wavefront:
  application:
    service: ${spring.application.name}

ribbon:
  http:
    client:
      enabled: false
