---
apiVersion: v1
kind: Service
metadata:
  name: todos-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-redis
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: boot
  selector:
    app: todos-redis
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todos-redis-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "todos-redis.{{ .Values.baseDomain }}"
  gateways:
  - todos-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: todos-redis
        port:
          number: 8888   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-redis
  template:
    metadata:
      name: todos-redis
      namespace: todos
      labels:
        app: todos-redis
    spec:
      containers:
        - image: {{ .Values.harborBase }}/todos-redis@{{ .Values.redisSha }}
          name: todos-redis
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: SPRING_REDIS_HOST
              value: "todos-redis-master"
            - name: SPRING_REDIS_PASSWORD
              value: "topsecret"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
              value: "todos-all"
          envFrom:
            - secretRef:
                name: wavefront
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888

