---
apiVersion: v1
kind: Service
metadata:
  name: todos-webui
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-webui
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: boot
  selector:
    app: todos-webui
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-webui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-webui
  template:
    metadata:
      name: todos-webui
      labels:
        app: todos-webui
    spec:
      containers:
        - image: {{ .Values.harborBase }}/todos-webui@{{ .Values.webuiSha }}
          name: todos-webui
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          env:
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
              value: "todos-all"
          envFrom:
            - secretRef:
                name: wavefront
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todos-webui-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "todos-webui.{{ .Values.baseDomain }}"
  gateways:
  - todos-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: todos-webui
        port:
          number: 8080
