---
apiVersion: v1
kind: Service
metadata:
  name: todos-service
  namespace: {{ .Values.namespace }}
  labels:
    app: todos-edge
spec:
  ports:
  - port: 9999
    targetPort: 9999
    name: boot
  selector:
    app: todos-edge
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-edge
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-edge
  template:
    metadata:
      name: todos-edge
      labels:
        app: todos-edge
    spec:
      containers:
      - image: {{ .Values.harborBase }}/todos-edge@{{ .Values.edgeSha }}
        name: todos-edge
        ports:
        - containerPort: 9999
          protocol: TCP
        env:
        - name: TODOS_API_ENDPOINT
          value: "http://todos-api:8081"
        - name: TODOS_UI_ENDPOINT
          value: "http://todos-webui:8080"
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: "true"
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
          value: "todos-all"
        envFrom:
            - secretRef:
                name: wavefront
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9999
---            
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todos-edge-vs
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - "todos.{{ .Values.baseDomain }}"
  gateways:
  - todos-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: todos-service
        port:
          number: 9999