apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: {{ .Values.wavefront.uri }}
  WAVEFRONT_APPLICATION_NAME: QURBTS1URVNUCg==