---
apiVersion: v1
kind: Service
metadata:
  name: todos-postgres
  labels:
    app: todos-postgres
spec:
  ports:
    - port: 9090
      targetPort: 9090
      name: boot
  selector:
    app: todos-postgres
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-postgres-ingress
spec:
  rules:
    - host: todos-postgres.{{ .Values.ingressUrl }}
      http:
        paths:
          - backend:
              serviceName: todos-postgres
              servicePort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-postgres
  template:
    metadata:
      name: todos-postgres
      labels:
        app: todos-postgres
    spec:
      containers:
        - image: {{ .Values.imageRepository }}/todos-postgres:latest
          name: todos-postgres
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
              value: "todos-all"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: todos-postgres
data:
  application.yml: |-
    spring:
      datasource:
        url: jdbc:postgresql://my-postgres-postgresql:5432/postgres
        username: postgres
        password: topsecret
