---
apiVersion: v1
kind: Service
metadata:
  name: todos-api
  labels:
    app: todos-api
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: boot
  selector:
    app: todos-api
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-api-ingress
spec:
  rules:
    - host: todos-api.{{ .Values.ingressUrl }}
      http:
        paths:
          - backend:
              serviceName: todos-api
              servicePort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      name: todos-api
      labels:
        app: todos-api
    spec:
      containers:
        - image: {{ .Values.imageRepository }}/todos-api:latest
          name: todos-api
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: CACHEURL
              value: "http://todos-redis:8888"
            - name: BACKENDURL
              value: "http://todos-postgres:9090"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
              value: "todos-all"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
