---
apiVersion: v1
kind: Service
metadata:
  name: todos-service
  labels:
    app: todos-edge
spec:
  ports:
  - port: 9999
    targetPort: 9999
    name: boot
  selector:
    app: todos-edge
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-edge
  template:
    metadata:
      name: todos-edge
      labels:
        app: todos-edge
    spec:
      containers:
      - image: {{ .Values.imageRepository }}/todos-edge:latest
        name: todos-edge
        ports:
        - containerPort: 9999
          protocol: TCP
        env:
        - name: TODOS_API_ENDPOINT
          value: "http://todos-api:8081"
        - name: TODOS_UI_ENDPOINT
          value: "http://todos-webui:8080"
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
          value: "true"
        - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
          value: "todos-all"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9999

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-edge-ingress
spec:
  rules:
    - host: todos-edge.{{ .Values.ingressUrl }}
      http:
        paths:
          - backend:
              serviceName: todos-service
              servicePort: 9999
