---
apiVersion: v1
kind: Service
metadata:
  name: todos-redis
  labels:
    app: todos-redis
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: boot
  selector:
    app: todos-redis
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-redis-ingress
spec:
  rules:
    - host: todos-redis.{{ .Values.ingressUrl }}
      http:
        paths:
          - backend:
              serviceName: todos-redis
              servicePort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-redis
  template:
    metadata:
      name: todos-redis
      labels:
        app: todos-redis
    spec:
      containers:
        - image: {{ .Values.imageRepository }}/todos-redis:latest
          name: todos-redis
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: SPRING_REDIS_HOST
              value: "todo-redis-instance-master"
            - name: SPRING_REDIS_PASSWORD
              value: "topsecret"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
              value: "todos-all"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888

