apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    scope: todos-all
type: Opaque
data:
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI: {{ .Values.wavefront.uri | b64enc }}
  MANAGEMENT_METRICS_EXPORT_WAVEFRONT_API_TOKEN: {{ .Values.wavefront.apiToken | b64enc }}
  WAVEFRONT_APPLICATION_NAME: {{ .Values.wavefront.application.name | b64enc }}
