apiVersion: v1
kind: Secret
metadata:
  name: wavefront
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    scope: todos-all
type: Opaque
data:
  "management.metrics.export.wavefront.uri": {{ .Values.wavefront.uri | b64enc }}
  "management.metrics.export.wavefront.apiToken": {{ .Values.wavefront.apiToken | b64enc }}
  "management.metrics.export.wavefront.application.name": {{ .Values.wavefront.application.name | b64enc }}
