---
apiVersion: v1
kind: Service
metadata:
  name: todos-webui
  labels:
    app: todos-webui
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: boot
  selector:
    app: todos-webui
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-webui
  template:
    metadata:
      name: todos-webui
      labels:
        app: todos-webui
    spec:
      containers:
        - image: harbor.tanzu.cloud.zwickey.net/library/todos-webui:latest
          name: todos-webui
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-webui-ingress
spec:
  rules:
    - host: todos-webui.tanzu.cloud.zwickey.net
      http:
        paths:
          - backend:
              serviceName: todos-webui
              servicePort: 8080
  tls:
    - hosts:
        - todos-webui.tanzu.cloud.zwickey.net
      secretName: ingress-tls