todos:
  api:
    limit: 1024
spring:
  application:
    name: todos-api
management:
  metrics:
    export:
      wavefront:
        #step: PT10S
        reporting:
          traces: true

  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081

wavefront:
  application:
    service: ${spring.application.name}
