todos:
  api:
    limit: 1024
spring:
  application:
    name: todos-api
management:
  metrics:
    export:
      wavefront:

        uri: https://vmware.wavefront.com
        apiToken: <TOKEN>
        step: PT10S

        reporting:
          #duration=(reporting duration, intervals between spring micrometer reporting)
          traces: true

        application:
          name: Todos Application
          service: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081