todos:
  api:
    limit: 1024
spring:
  application:
    name: todos-api
management:
  metrics:
    export:
      wavefront:
        api-token: 157e88c4-d030-44d4-b65a-9a7a1caf3c38
        step: PT10S
        reporting:
          traces: true

  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8081

wavefront:
  application:
    service: ${spring.application.name}
