---
apiVersion: v1
kind: Service
metadata:
  name: todos-redis
  namespace: todos
  labels:
    app: todos-redis
spec:
  ports:
    - port: 8888
      targetPort: 8888
      name: boot
  selector:
    app: todos-redis
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todos-redis-vs
  namespace: todos
spec:
  hosts:
  - "todos-redis.mesh.workload1.tanzu.zwickey.net"
  gateways:
  - todos-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: todos-redis
        port:
          number: 8888   
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: todos-redis-ingress
  namespace: todos
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
spec:
  tls:
  - secretName: todos-redis-secret
    hosts:
      - todos-redis.workload1.tanzu.zwickey.net
  rules:
    - host: todos-redis.workload1.tanzu.zwickey.net
      http:
        paths:
          - backend:
              serviceName: todos-redis
              servicePort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-redis
  namespace: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-redis
  template:
    metadata:
      name: todos-redis
      namespace: todos
      labels:
        app: todos-redis
    spec:
      containers:
        - image: harbor.mgmt.tanzu.zwickey.net/library/todos-redis:latest
          name: todos-redis
          ports:
            - containerPort: 8888
              protocol: TCP
          env:
            - name: SPRING_REDIS_HOST
              value: "todos-redis-master"
            - name: SPRING_REDIS_PASSWORD
              value: "topsecret"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: "true"
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_LABELS_SCOPE
              value: "todos-all"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888

